Repository MentoMate/mentomate-FE, pull requests merged in 2023-10, with the labels that each got.

#1 Feature/sign up page UI
  package-lock.json
  package.json
  src/assets/svg/Logo.svg
  src/assets/svg/checkmark.svg
  src/assets/svg/email.svg
  src/assets/svg/googleLogo.svg
  src/assets/svg/kakaoTalkLogo.svg
  src/assets/svg/naverLogo.svg
  src/components/choiceSignUpType/ChoiceSignUpType.tsx
  src/components/signUp/SignUp.tsx
  src/components/signUp/SignUpForm.tsx
  src/modules/svg.d.ts
  src/pages/ChoiceSignUpTypePage.tsx
  src/pages/SignUpPage.tsx
  tsconfig.json
  vite.config.ts
Labels: component

#4 login page UI 생성
  src/components/login/Login.tsx
  src/components/login/LoginForm.tsx
  src/components/login/SocialLogin.tsx
  src/pages/LoginPage.tsx
Labels: component

#8 page routing 추가, suspense 코드 추가, spinner 라이브러리 추가
  package-lock.json
  package.json
  src/components/choiceSignUpType/ChoiceSignUpType.tsx
  src/components/choiceSignUpType/SignUpType.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/headerLeft/HeaderLeftContainer.tsx
  src/components/common/header/headerLeft/Menu.tsx
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/common/header/headerRight/BeforeLogin.tsx
  src/components/common/header/headerRight/HeaderRightContainer.tsx
  src/components/common/spinner/Spinner.tsx
  src/components/login/Login.tsx
  src/components/login/LoginForm.tsx
  src/components/login/SocialLogin.tsx
  src/components/signUp/SignUp.tsx
  src/components/signUp/SignUpForm.tsx
  src/pages/ChoiceSignUpTypePage.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  tailwind.config.js
Labels: component

#14 Merge: 레포지토리 절대경로 설정, 카테고리 모달UI 생성
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/image/sample.jpg
  src/assets/svg/blackCalendar.svg
  src/assets/svg/bottom_arrow.svg
  src/assets/svg/cash.svg
  src/assets/svg/category.svg
  src/assets/svg/close.svg
  src/assets/svg/people.svg
  src/assets/svg/search.svg
  src/assets/svg/star.svg
  src/components/choiceSignUpType/ChoiceSignUpType.tsx
  src/components/choiceSignUpType/SignUpType.tsx
  src/components/common/footer/Footer.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/headerLeft/HeaderLeftContainer.tsx
  src/components/common/header/headerLeft/Menu.tsx
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/common/header/toggle/Toggle.tsx
  src/components/login/Login.tsx
  src/components/login/SocialLogin.tsx
  src/components/mentoring/Mentoring.tsx
  src/components/mentoring/MentoringTitle.tsx
  src/components/mentoring/Search/Category.tsx
  src/components/mentoring/Search/Keyword.tsx
  src/components/mentoring/Search/Search.tsx
  src/components/mentoring/Search/Sort.tsx
  src/components/mentoring/categoryModal/CategoryList.tsx
  src/components/mentoring/categoryModal/CategoryModal.tsx
  src/components/mentoring/categoryModal/SelectCategoryType.tsx
  src/components/mentoring/categoryModal/TitleBarWithClose.tsx
  src/components/mentoring/mentoringList/MentoringItem.tsx
  src/components/mentoring/mentoringList/MentoringList.tsx
  src/components/mentoring/mentoringList/NonExistMentoringList.tsx
  src/components/signUp/SignUp.tsx
  src/constants/categories.ts
  src/hooks/useBodyScrollLock.ts
  src/input.css
  src/pages/ChoiceSignUpTypePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MentoringPage.tsx
  src/pages/SignUpPage.tsx
  src/state/openCategoryModal.ts
  src/state/selectedCategory.ts
  src/types/categoty.ts
  tsconfig.json
  vite.config.ts
Labels: component, feature

#15 Merge: Feature/menoring page UI
  src/Router.tsx
  src/assets/image/sample.jpg
  src/assets/svg/blackCalendar.svg
  src/assets/svg/bottom_arrow.svg
  src/assets/svg/cash.svg
  src/assets/svg/category.svg
  src/assets/svg/close.svg
  src/assets/svg/people.svg
  src/assets/svg/search.svg
  src/assets/svg/star.svg
  src/components/common/header/Header.tsx
  src/components/common/header/headerLeft/Menu.tsx
  src/components/mentoring/Mentoring.tsx
  src/components/mentoring/MentoringTitle.tsx
  src/components/mentoring/Search/Category.tsx
  src/components/mentoring/Search/Keyword.tsx
  src/components/mentoring/Search/Search.tsx
  src/components/mentoring/Search/Sort.tsx
  src/components/mentoring/categoryModal/CategoryList.tsx
  src/components/mentoring/categoryModal/CategoryModal.tsx
  src/components/mentoring/categoryModal/SelectCategoryType.tsx
  src/components/mentoring/categoryModal/TitleBarWithClose.tsx
  src/components/mentoring/mentoringList/MentoringItem.tsx
  src/components/mentoring/mentoringList/MentoringList.tsx
  src/components/mentoring/mentoringList/NonExistMentoringList.tsx
  src/constants/categories.ts
  src/hooks/useBodyScrollLock.ts
  src/input.css
  src/pages/MentoringPage.tsx
  src/state/openCategoryModal.ts
  src/state/selectedCategory.ts
  src/types/categoty.ts
Labels: component

#21 PR : feature/mentorDetailPageUI
  src/Router.tsx
  src/components/mentorDetail/MentorDetailContainer.tsx
  src/components/mentorDetail/MentorInfo.tsx
  src/components/mentorDetail/MentorIntroduce.tsx
  src/components/mentorDetail/mentorReivew/MentorReviewContainer.tsx
  src/components/mentorDetail/mentorReivew/MentorReviewItems.tsx
  src/components/mentorDetail/mentorReivew/MentorReviewList.tsx
  src/components/mentorDetail/mentorReivew/NonExistsReview.tsx
  src/components/mentorDetail/pastMentoring/NonExistsPastMentoring.tsx
  src/components/mentorDetail/pastMentoring/PastMentoringContainer.tsx
  src/components/mentorDetail/pastMentoring/PastMentoringItem.tsx
  src/components/mentorDetail/pastMentoring/PastMentoringList.tsx
  src/input.css
  src/pages/MentorDetailPage.tsx
Labels: component

#23 PR : Feature/itemhoverscale
  src/components/choiceSignUpType/ChoiceSignUpTypeContainer.tsx
  src/components/login/LoginContainer.tsx
  src/components/mentor/mentoringList/MentorItem.tsx
  src/components/mentoring/MentoringContainer.tsx
  src/components/mentoring/mentoringList/MentoringItem.tsx
  src/components/signUp/SignUpContainer.tsx
  src/pages/ChoiceSignUpTypePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MentoringPage.tsx
  src/pages/SignUpPage.tsx
Labels: component

#25 PR : fix/noUse
  src/components/main/thirdsection/MentorCard.tsx
Labels: bug

#38 PR : Feature/registerMentor
  src/Router.tsx
  src/assets/svg/emptyHeart.svg
  src/assets/svg/fillHeart.svg
  src/assets/svg/registerMentor.svg
  src/assets/svg/share.svg
  src/components/community/communityList/CommunityItem.tsx
  src/components/communityDetail/CommunityContent.tsx
  src/components/communityDetail/CommunityDetailContainer.tsx
  src/components/communityDetail/CommunityLikeAndComment.tsx
  src/components/communityDetail/CommunitySideBar.tsx
  src/components/communityDetail/CommunityWriterInfo.tsx
  src/components/communityDetail/comment/Comment.tsx
  src/components/communityDetail/comment/CommentContainer.tsx
  src/components/communityDetail/comment/CommentSubmit.tsx
  src/components/mentor/MentorRegister.tsx
  src/components/mentorRegistration/MentorRegistrationContainer.tsx
  src/components/mentorRegistration/PrevAndNextButton.tsx
  src/components/mentorRegistration/registrationStep/FirstStep.tsx
  src/components/mentorRegistration/registrationStep/RegistartionStepContainer.tsx
  src/components/mentorRegistration/registrationStep/SecondStep.tsx
  src/components/mentorRegistration/registrationStep/ThirdStep.tsx
  src/hooks/useAlert.ts
  src/input.css
  src/pages/CommunityDetailPage.tsx
  src/pages/MentorRegistrationPage.tsx
  src/state/mentorRegistrationStep.ts
Labels: component

#40 PR : feature/proxy
  vite.config.ts
Labels: feature

#41 PR : feature/registerMentoringPage
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/svg/checklist.svg
  src/assets/svg/tidle.svg
  src/assets/svg/wonSign.svg
  src/components/mentoringRegistration/MentoringRegistrationContainer.tsx
  src/components/mentoringRegistration/MentoringTitle.tsx
  src/components/mentoringRegistration/SaveAndBackButton.tsx
  src/components/mentoringRegistration/essentialInfo/EsseentialPrice.tsx
  src/components/mentoringRegistration/essentialInfo/EssentialCategory.tsx
  src/components/mentoringRegistration/essentialInfo/EssentialHeadCount.tsx
  src/components/mentoringRegistration/essentialInfo/EssentialInfoContainer.tsx
  src/components/mentoringRegistration/essentialInfo/EssentialMentoringPeriod.tsx
  src/pages/MentoringRegistrationPage.tsx
Labels: component

#49 PR : feature/mypageUI
  src/Router.tsx
  src/assets/svg/Home.svg
  src/assets/svg/alarm.svg
  src/assets/svg/arrow.svg
  src/assets/svg/group.svg
  src/assets/svg/logout.svg
  src/assets/svg/mentoringfavorite.svg
  src/components/mypage/MypageContainer.tsx
  src/components/mypage/MypageContent.tsx
  src/components/mypage/MypageList.tsx
  src/components/mypage/mypagealarm/MypageAlarm.tsx
  src/components/mypage/mypagefavoritementoring/MypageFavoriteMentoring.tsx
  src/components/mypage/mypagefavoritementoring/MypageMentoring.tsx
  src/components/mypage/mypagefavoritementoring/MypageMentoringList.tsx
  src/components/mypage/mypagefollow/MentorItem.tsx
  src/components/mypage/mypagefollow/MypageFollow.tsx
  src/components/mypage/mypageinfo/MypageInfo.tsx
  src/components/mypage/mypagemain/MyPageMain.tsx
  src/components/mypage/mypagemain/MypageMentoring.tsx
  src/components/mypage/mypagemain/MypageMentoringList.tsx
  src/components/mypage/mypagemymentoring/MypageMentoring.tsx
  src/components/mypage/mypagemymentoring/MypageMentoringList.tsx
  src/components/mypage/mypagemymentoring/MypageMyMentoring.tsx
  src/components/mypage/mypagepayment/MypagePayment.tsx
  src/components/mypage/mypagepayment/MypagePaymentCard.tsx
  src/components/mypage/mypagereview/MypageMentoring.tsx
  src/components/mypage/mypagereview/MypageMentoringList.tsx
  src/components/mypage/mypagereview/MypageReview.tsx
  src/components/mypage/mypagewriting/CommunityItem.tsx
  src/components/mypage/mypagewriting/CommunityList.tsx
  src/components/mypage/mypagewriting/MypageWriting.tsx
  src/pages/MyPage.tsx
  src/types/mypagelistprop.ts
Labels: component

#50 PR : feature/socialLogin
  index.html
  src/Router.tsx
  src/components/choiceSignUpType/SignUpType.tsx
  src/components/login/KaKaoCallback.tsx
  src/components/login/LoginForm.tsx
  src/components/login/NaverCallback.tsx
  src/components/login/OauthRedirect.tsx
  src/components/login/SocialLogin.tsx
  src/components/mentor/MentorRegister.tsx
  src/components/mentoring/MentoringTitle.tsx
  src/hooks/useCheckAuth.ts
  src/pages/MentorRegistrationPage.tsx
  src/pages/MentoringRegistrationPage.tsx
Labels: feature

#60 PR : Feature/socialSignUp
  .gitignore
  src/components/login/KaKaoCallback.tsx
  src/components/login/NaverCallback.tsx
  src/components/login/SocialLogin.tsx
Labels: feature
