Repository MentoMate/mentomate-FE, pull requests merged in 2023-11, with the labels that each got.

#63 Feature/mentor registration
  package-lock.json
  package.json
  src/components/mentorRegistration/MentorRegistrationContainer.tsx
  src/components/mentorRegistration/PrevAndNextButton.tsx
  src/components/mentorRegistration/registrationStep/RegistartionStepContainer.tsx
  src/components/mentorRegistration/registrationStep/ThirdStep.tsx
  src/components/signUp/SignUpForm.tsx
  src/data/mentorRegistrationData.ts
  src/utils/regex.ts
Labels: feature

#65 PR : feature/payment
  .env
  src/Router.tsx
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/mentoringDetail/mentoringInfoWithApply/Button.tsx
  src/components/mentoringpayment/PaymentConfirmation.tsx
  src/components/mentoringpayment/PaymentSuccess.tsx
  src/hooks/useCheckAuth.ts
  src/pages/PaymentPage.tsx
  src/pages/PaymentSuccessPage.tsx
Labels: feature

#67 PR : Feature/mentoringDetailEditDelete
  src/Router.tsx
  src/components/login/LoginForm.tsx
  src/components/mentorRegistration/registrationStep/ThirdStep.tsx
  src/components/mentoring/mentoringList/MentoringList.tsx
  src/components/mentoringDetail/MentoringDetailContainer.tsx
  src/components/mentoringDetail/mentoringInfoWithApply/MentoringContent.tsx
  src/components/mentoringDetail/mentoringInfoWithApply/MentoringInfo.tsx
  src/components/mentoringDetail/mentoringInfoWithApply/MentoringInfoWithApply.tsx
  src/components/mentoringEdit/MentoringEditContainer.tsx
  src/components/mentoringEdit/MentoringTitle.tsx
  src/components/mentoringEdit/SaveAndBackButton.tsx
  src/components/mentoringEdit/essentialInfo/EsseentialPrice.tsx
  src/components/mentoringEdit/essentialInfo/EssentialCategory.tsx
  src/components/mentoringEdit/essentialInfo/EssentialHeadCount.tsx
  src/components/mentoringEdit/essentialInfo/EssentialInfoContainer.tsx
  src/components/mentoringEdit/essentialInfo/EssentialMentoringPeriod.tsx
  src/data/mentoringEditForm.ts
  src/hooks/useAxios.ts
  src/interface/mentoringInfo.ts
  src/main.tsx
  src/pages/MentoringEditPage.tsx
Labels: feature

#68 PR : Feature/mentoringRegistration
  src/components/community/CommnunityContainer.tsx
  src/components/mentoringRegistration/MentoringRegistrationContainer.tsx
  src/components/mentoringRegistration/MentoringTitle.tsx
  src/components/mentoringRegistration/SaveAndBackButton.tsx
  src/components/mentoringRegistration/essentialInfo/EsseentialPrice.tsx
  src/components/mentoringRegistration/essentialInfo/EssentialHeadCount.tsx
  src/components/mentoringRegistration/essentialInfo/EssentialInfoContainer.tsx
  src/components/mentoringRegistration/essentialInfo/EssentialMentoringPeriod.tsx
  src/data/mentoringRegistrationData.ts
Labels: feature

#69 PR : feature/MentoringfileUpload
  src/assets/svg/edit.svg
  src/assets/svg/filelist.svg
  src/components/login/KaKaoCallback.tsx
  src/components/mentoringRoom/Calender.tsx
  src/components/mentoringRoom/DayCellContent.tsx
  src/components/mentoringRoom/FileUpload.tsx
  src/components/mentoringRoom/MentoringFileList.tsx
  src/components/mentoringRoom/MentoringInfoModal.tsx
  src/components/mentoringRoom/MentoringRoom.tsx
  src/components/mentoringRoom/ScduleAddModal.tsx
  src/components/mentoringRoom/ScduleEdit.tsx
  src/components/mentoringRoom/ScduleReadModal.tsx
  src/pages/MentoringRoomPage.tsx
Labels: component

#73 PR : refactor/refactor
  src/components/login/SocialLogin.tsx
  src/components/main/MentoringCard.tsx
  src/components/main/fifthsection/DeadlineMentoringList.tsx
  src/components/main/fifthsection/FifthSection.tsx
  src/components/main/firstsection/FirstSection.tsx
  src/components/main/firstsection/MentoringCardList.tsx
  src/components/main/fourthsection/FourthSection.tsx
  src/components/main/secondsection/SecondSection.tsx
  src/components/main/sixsection/SixSection.tsx
  src/components/main/thirdsection/MentorCard.tsx
  src/components/main/thirdsection/MentorCardList.tsx
  src/components/main/thirdsection/ThirdSection.tsx
  src/components/mentoringRoom/Calender.tsx
  src/components/mentoringRoom/FileUpload.tsx
  src/components/mentoringRoom/ScheduleAddModal.tsx
  src/components/mentoringRoom/ScheduleEdit.tsx
  src/components/mentoringRoom/ScheduleReadModal.tsx
  src/components/mentoringpayment/PaymentConfirmation.tsx
  src/components/mypage/MypageContent.tsx
  src/interface/mainPageMentoringCard.ts
  src/main.tsx
  src/types/daycellcontentprop.ts
Labels: refactor

#74 PR : feature/mentor
  src/Router.tsx
  src/components/mentor/MentorContainer.tsx
  src/components/mentor/mentoringList/MentorItem.tsx
  src/components/mentor/mentoringList/MentorList.tsx
  src/components/mentorDetail/MentorDetailContainer.tsx
  src/components/mentorDetail/MentorInfo.tsx
  src/components/mentorDetail/MentorIntroduce.tsx
  src/interface/mentorItem.ts
Labels: feature

#79 PR : Feature/community
  index.html
  src/Router.tsx
  src/components/community/CommnunityContainer.tsx
  src/components/community/CommunityContainer.tsx
  src/components/community/CommunityTab.tsx
  src/components/community/LocationWithCreate.tsx
  src/components/community/communityList/CommunityItem.tsx
  src/components/community/communityList/CommunityList.tsx
  src/components/communityDetail/CommunityContent.tsx
  src/components/communityDetail/CommunityDetailContainer.tsx
  src/components/communityDetail/CommunityLikeAndComment.tsx
  src/components/communityDetail/CommunitySideBar.tsx
  src/components/communityDetail/CommunityWriterInfo.tsx
  src/components/communityDetail/comment/Comment.tsx
  src/components/communityDetail/comment/CommentContainer.tsx
  src/components/communityDetail/comment/CommentList.tsx
  src/components/communityDetail/comment/CommentSubmit.tsx
  src/components/communityDetail/comment/NonExistsComment.tsx
  src/components/communityEdit/EditCommunityContainer.tsx
  src/components/communityEdit/EditCommunitySaveAndBackButton.tsx
  src/components/communityEdit/EditCommunityTitle.tsx
  src/components/communityEdit/essentialInfo/EditChoiceCommunityType.tsx
  src/components/communityEdit/essentialInfo/EditEssentialInfoContainer.tsx
  src/components/communityEdit/essentialInfo/EditThumbNail.tsx
  src/components/communityRegistration/CommunityRegistrationContainer.tsx
  src/components/communityRegistration/CommunityTitle.tsx
  src/components/communityRegistration/SaveAndBackButton.tsx
  src/components/communityRegistration/essentialInfo/ChoiceCommunityType.tsx
  src/components/communityRegistration/essentialInfo/EssentialInfoContainer.tsx
  src/components/communityRegistration/essentialInfo/ThumNail.tsx
  src/data/communityRegistrationForm.ts
  src/interface/comment.ts
  src/interface/community.ts
  src/pages/CommunityPage.tsx
  src/pages/CommunityRegistrationPage.tsx
  src/pages/EditCommunityPage.tsx
Labels: feature

#80 PR : feature/tailwind
  index.html
  package-lock.json
  package.json
  postcss.config.cjs
  postcss.config.js
  src/main.tsx
  tailwind.config.js
Labels: feature

#86 PR : feature/mentorinDetailProfileImg
  src/components/mentoringDetail/MentorProfile.tsx
  src/interface/mentoringInfo.ts
Labels: feature

#90 PR : Feature/pushAlert
  package-lock.json
  package.json
  src/Router.tsx
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/common/header/headerRight/Notification.tsx
  src/state/notification.ts
  src/state/searchUrl.ts
  tailwind.config.js
Labels: feature

#92 ♻️ refactor: code refactor
  src/components/mentoringRoom/Calendar.tsx
  src/components/mentoringRoom/ScheduleAddButton.tsx
  src/components/mentoringRoom/ScheduleAddModal.tsx
Labels: refactor

#93 PR : feature/deleteEmitter
  src/Router.tsx
  src/components/common/header/headerRight/AfterLogin.tsx
  src/components/communityDetail/CommunitySideBar.tsx
  src/state/notification.ts
Labels: feature

#94 PR : Feature/commintyQuery
  src/components/common/pagination/Pagination.tsx
  src/components/common/search/Sort.tsx
  src/components/common/searchType/SearchType.tsx
  src/components/community/CommunityContainer.tsx
  src/components/community/LocationWithCreate.tsx
  src/components/community/communityList/CommunityItem.tsx
  src/components/community/communityList/CommunityList.tsx
  src/components/community/communitySearch/SearchCriteriaWithKeyword.tsx
  src/components/communityDetail/comment/CommentContainer.tsx
  src/components/communityDetail/comment/CommentList.tsx
  src/components/communityDetail/comment/CommentSubmit.tsx
  src/components/mentor/MentorContainer.tsx
  src/components/mentoring/MentoringContainer.tsx
  src/hooks/useUrl.ts
  src/interface/comment.ts
  src/main.tsx
  src/pages/CommunityPage.tsx
Labels: feature

#96 PR: feature/paymentAPI
  src/Router.tsx
  src/components/mentoring/mentoringList/MentoringList.tsx
  src/components/mentoringDetail/MentoringDetailContainer.tsx
  src/components/mentoringDetail/mentoringInfoWithApply/Button.tsx
  src/components/mentoringDetail/mentoringInfoWithApply/MentoringInfoWithApply.tsx
  src/components/mentoringpayment/PaymentConfirmation.tsx
  src/pages/PaymentPage.tsx
Labels: feature

#98 PR : Feature/chat
  package-lock.json
  package.json
  src/Router.tsx
  src/assets/svg/chatComment.svg
  src/assets/svg/chatEmotion.svg
  src/assets/svg/list.svg
  src/assets/svg/notFound.svg
  src/components/common/chatAndScrollTop/ChatAndScrollContainer.tsx
  src/components/common/chatAndScrollTop/ScrollTopBtn.tsx
  src/components/common/chatAndScrollTop/chat/Chat1On1.tsx
  src/components/common/chatAndScrollTop/chat/ChatBtn.tsx
  src/components/common/chatAndScrollTop/chat/ChatModalContainer.tsx
  src/components/common/chatAndScrollTop/chat/chatList/ChatListContainer.tsx
  src/components/common/chatAndScrollTop/chat/chatList/ExistsChatList.tsx
  src/components/common/chatAndScrollTop/chat/chatList/NonExistsChatList.tsx
  src/components/common/header/headerRight/Notification.tsx
  src/components/community/CommunityContainer.tsx
  src/components/login/KaKaoCallback.tsx
  src/components/login/LoginForm.tsx
  src/components/login/NaverCallback.tsx
  src/components/mentor/MentorContainer.tsx
  src/components/mentoring/MentoringContainer.tsx
  src/components/mentoringDetail/mentoringInfoWithApply/Button.tsx
  src/components/mentoringDetail/mentoringInfoWithApply/MentoringInfoWithApply.tsx
  src/components/notFound404/NotFound404.tsx
  src/constants/commonComponentLocation.ts
  src/data/chatHistory.ts
  src/input.css
  src/interface/chat.ts
  src/pages/CommunityDetailPage.tsx
  src/pages/CommunityPage.tsx
  src/pages/CommunityRegistrationPage.tsx
  src/pages/EditCommunityPage.tsx
  src/pages/MainPage.tsx
  src/pages/MentorDetailPage.tsx
  src/pages/MentorPage.tsx
  src/pages/MentorRegistrationPage.tsx
  src/pages/MentoringDetailPage.tsx
  src/pages/MentoringEditPage.tsx
  src/pages/MentoringPage.tsx
  src/pages/MentoringRegistrationPage.tsx
  src/pages/NotFound404Page.tsx
  src/state/chatState.ts
  vite.config.ts
Labels: feature

#125 PR: fix/mentoringRoomFix
  src/components/mentoringRoom/Calendar.tsx
  src/components/mentoringRoom/DayCellContent.tsx
  src/components/mentoringRoom/MentoringEndButton.tsx
  src/components/mentoringRoom/MentoringInfoModal.tsx
  src/components/mentoringRoom/ScheduleReadModal.tsx
  src/state/mentorState.ts
Labels: bug

#126 PR : Refactor/refact
  README.md
  public/mentorMateBanner.jpg
  public/mentoringImage.jpg
  src/components/communityDetail/CommunityDetailContainer.tsx
  src/components/main/BannerSection.tsx
  src/components/main/MentoringCard.tsx
  src/components/mentor/MentorRegister.tsx
  src/components/mentorDetail/MentorDetailContainer.tsx
  src/components/mentoringEdit/EditMentoringContainer.tsx
  src/hooks/usePagination.ts
Labels: refactor
